### ISSUE TITLE
Module modernization and cleanup

### ISSUE THREAD

**Issue by smortex** [voxpupuli/puppet-poudriere#52]
While working on #51, I spotted a bunch of things that where beyond the scope of this PR but where annoying / weird for me, so I open this issue to list these points so that maintainers can tell what they thing about it and we can track the overall progress.

Here is a checklist of the things I spotted and am willing to fix.  I propose to have these items checked when the maintainers are OK with it, then add a link to a PR when one is ready, and ~~strike-out~~ the lines when the PR are merged.

* [x] #51 (merged) — Add data-types for all parameters
* [x] #53 (merged) — The module use default values of `''` for optional values… Change these to `undef` and use a `Optional[String[1]]` data type for these items
* [x] `poudriere::zpool` default value is currently `tank`, a term commonly found with ZFS but is the name of the pool the end-user want sot use only when they are super-lucky…  Maybe it's worth change it:
  * [x] #53 (merged) — default `poudriere::zpool` to undef (do not set a default value, poudriere can work without ZFS (at least, support for this was added at some point))
  * [x] (abandoned) ~~default `poudriere::zpool` to `zroot` (default pool name when installing FreeBSD with ZFS on root)~~
* [x] #56 (merged) — `poudriere::freebsd_host` default to a specific mirror, change it to `http://ftp.FreeBSD.org/`, which is [made up of many machines operated by the project cluster administrators and behind GeoDNS to direct users to the closest available mirror](https://docs.freebsd.org/doc/12.1-RELEASE/usr/local/share/doc/freebsd/en/books/handbook/mirrors-ftp.html)
* [x] #54 (merged) — The default version of `env::architecture` is hardcoded to amd64. Default to the architecture of the node.
* [x] #57 (merged) — The default version of `env::version` is hardcoded to an old release. Default to undef and force the user to specify explicitly what version they want.
* [x] #58 (merged) Sync configuration file parameters with latest poudriere settings
* [ ] #61 Switch from ERB to EPP
* [x] #58 (1/2, merged), #59 (2/2, merged) — Extend the test suite with tests that set *all* parameters (we seem to have some parameters which lead to broken catalogs when used)
